info:
  app:
    name: AronimCloudComponentService
    description: Aronim Cloud Component Service
    version: 1.0-SNAPSHOT

spring:
  application:
    name: aronim-cloud-component

server:
  port: 0
