info:
  app:
    name: KdcCloudComponentService
    description: KungfuDev Cloud Component Service
    version: 1.0-SNAPSHOT

spring:
  application:
    name: aronim-cloud-component

server:
  port: 0
